name: Add Mask
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    env:
      SEACRET_SOMETHING: SuperSecret
    steps:
      - run: echo "::add-mask::${SEACRET_SOMETHING}"
      - run: echo "${SEACRET_SOMETHING}"