name: Artifacts
on: push
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: date > date.txt
      - uses: actions/upload-artifact@v5
        with:
          name: uploaded # アーティファクトの名前
          path: date.txt # アーティファクトのパス
          retention-days: 7 # 保存期間
  download:
    runs-on: ubuntu-latest
    needs: [upload]
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: uploaded
          path: downloaded
      - run: cat downloaded/date.txt
