name: Manual Matrix
on: push
jobs:
  matrixjob:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            version: 18
          - os: ubuntu-latest
            version: 20
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.version }}
      - run: echo "OS is ${RUNNER_OS}" && node --version
      