name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'   # セマンティックバージョニング
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: |                        # リリース対象アプリケーションのビルド
          go build -ldflags "-X main.version=${VERSION}" \
            -o "${RUNNER_TEMP}/example" go/example/main.go
      - run: |
          gh relese create "${VERSION}" --title "${VERSION}" --generate-notes
          gh relese upload "${VERSION}" "${RUNNER_TEMP}/example"