name: Secret
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
      MY_SECRET: ${{ secrets.MY_SECRET }}
    steps:
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD#?}"
      - run: echo "${MY_SECRET}"
      - run: echo "${MY_SECRET#?}"