name: Skip job condition
on: push
jobs:
  skip-or-run:
    if: ${{ github.actor == 'octocat' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${ACTOR}"
        env:
          ACTOR: ${{ github.actor }}